<a href="https://colab.research.google.com/github/Datebi/Python-Practice/blob/Datebi-CoderhouseCoursePractice/2.Arrays_Baigorria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

>> Consigna: 
1.Generar un array aleatorio de 100 elementos. 
2.Calcular la mediana correspondiente.
3.Recordar los ejercicios con funciones para cálculo de factorial y suma de serie de la Clase 02. Repetir ambos ejercicios, pero ahora utilizar las nuevas operaciones aprendidas con los ndarrays.
4.En este link se provee un archivo con los resultados de la Encuesta de Sueldos de Openqube de Febrero 2020 (https://sueldos.openqube.io/encuesta-sueldos-2020.02/ ), Calcular y comparar media y mediana de los sueldos netos.

>>Aspectos a incluir en el entregable:
El código debe estar hecho en un notebook y debe estar probado.


In [ ]:
>>> 1.

import numpy as np
import random


Npa = np.random.randint(1000,size=(100))
Npa

array([ 57, 403, 756, 292, 948, 601, 225,  68, 651, 981, 226, 428, 767,
       798, 913, 174, 806, 594, 268, 882, 978,  74, 896, 645, 498, 461,
       371, 275, 615, 992, 856, 498, 653, 631, 421, 360, 335, 705, 829,
       660, 426, 440, 827, 568, 832, 766, 409, 134, 393, 856, 763, 761,
       339, 308, 928, 444, 293, 828, 532, 903, 496, 945, 464, 696, 175,
       901, 553, 788, 137, 358, 489, 159,   6, 570,  47, 969, 433,  70,
       600, 818, 740, 881, 172,  23, 975, 820, 700, 496, 768, 676, 883,
       451, 869, 805, 575, 699, 748, 457, 399, 934])

In [ ]:
>>> 2.

np.median(Npa)

597.0

In [ ]:
>>> 3.

from scipy.special import factorial
import numpy as np

array = np.array([[6,1,3],[2,4,1]])

print(factorial(array))

[[720.   1.   6.]
 [  2.  24.   1.]]


In [ ]:
>>> 4.

import numpy as np

array = np.array([1,4])
suma=1


for i in range(array[0],array[1]):
    suma += array[0]+i
print(suma)


10


In [ ]:
>>> 5. 

import numpy as np
import csv



filename = 'Salarios Openqube.csv'
raw_data = open(filename)
data = np.genfromtxt(raw_data, skip_header = 1, dtype=float, usecols=np.arange(0,1))
print(data.shape)
print(data)


(6198,)
[4.30e+04 6.30e+04 1.27e+05 ...      nan 7.20e+01 6.50e+04]


# Sección nueva

In [ ]:
import numpy


data = data[numpy.logical_not(numpy.isnan(data))]
np.average(data)

19362252.577376597

In [ ]:
np.median(data)

76000.0